### ISSUE TITLE
Some function are not defined

### ISSUE THREAD

**Issue by Mostafa-Atallah2020** [alastair-marshall/QuOptimalControl.jl#5]
![image](https://user-images.githubusercontent.com/67621237/111924730-9ee9d800-8aae-11eb-8600-c5e339463dc5.png)

I am having this error every time I run one of the package examples.

**Comment by alastair-marshall** [comment]
Hey @Mostafa-Atallah2020 , I am sorry this issue sat open for so long!

I've fixed a bunch of bugs in the past few days so if you try again hopefully it'll work!

**Comment by alastair-marshall** [comment]
I think this bug is gone, tests pass and the code has changed substantially! Cool to have my first issue, just sorry you saw the code in this state!
